### ISSUE TITLE
netapp.aws 21.7.1 is not tagged

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/netapp.aws#8]
### Summary

Hi! As part of the ansible community package release process, we've determined that version 21.7.1 of netapp.aws was released to Ansible Galaxy but not properly tagged in this Git repository. This violates the [repository management](https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#repository-management) section of the Collection Requirements:

> Every collection MUST have a public git repository. Releases of the collection MUST be tagged in said repository. This means that releases MUST be git taged and that the tag name MUST exactly match the Galaxy version number. Tag names MAY have a v prefix, but a collection's tag names MUST have a consistent format from release to release.
>
> Additionally, collection artifacts released to Galaxy MUST be built from the sources that are tagged in the collection's git repository as that release. Any changes made during the build process MUST be clearly documented so the collection artifact can be reproduced.

If the collection maintainers do not respond to this issue within a reasonable a amount of time, the collection is subject to [Removal from ansible](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#collections-not-satisfying-the-collection-requirements).

### Component Name

collection

### Ansible Version

```console
all
```

### CVS for AWS Collection Version

```console
latest
```

### Playbook

```console
irrelevant
```

### Steps to Reproduce

irrelevant

### Expected Results

irrelevant

### Actual Results

```console
irrelevant
```

**Comment by felixfontein** [comment]
@carchi8py ping!

**Comment by felixfontein** [comment]
@carchi8py @lonico please take a look at this issue and make sure the release is tagged.

**Comment by carchi8py** [comment]
@felixfontein Fixed this.

**Comment by felixfontein** [comment]
Thanks for tagging the release! I removed the pin in https://github.com/ansible-community/ansible-build-data/pull/311.
